language: node_js
node_js:
 - 8

deploy:
  provider: heroku
  api_key:
    secure: "EYWEHgqXUxe/b3mZUuBZgx2UPLctL9f+37m5JbcN2HZF+mwV51Aoh+Qv4syw//vc2JmPCYVioUW7Oxv0fQROFzY8AVIYPqF/HgtHov6UwCGiXheizQwyhq38hlg8l5tplhSfXKf41V1Im61+bnQc6a3I4C/jNBioFMlp9MryVkVaAitX6ryshj7hxRpYX21SU6t8vijIMcbvXjyqhYl9H3XyXlsRPg72aV3pbZtkjAOFLxt8KdI5UVraJvS3GMIbkDPFbyrI0p6fDONCjJ+bOzXFh1r1hq+wEYE1rmIQDT9vNHpSkft2ta/1Z27xW08H5Tfy3hftMvEPMI1uFIQsFc+ei96N8HrHZYIi+ympGsRWHULE8VKMeBD8erRgq6/JWJVPRszF/YGKhDNE+6cPKgR5X44j9JraczxWh0qz8XouMYRy6ZRsOlBWGgQnrpwcaAE4xP5JtX+WePNj/AT8r+HzV3WMKstUX+jchPvUaHa6uI4SEDTlOHO1hCaT8UEgSFMFbZnjMGkT45bu1rhjP8VpXZ9sSArUOGwBWMU+rD7MeV9i2N2GrLZpHNqDNfFs/yUYGQkVlPv22pr/Cu2c0q19YI3179leuaK/yy6QsgzwAs3CHjzY/kGWmeZZY2yGWEeNatrtqAgvyNOVvjZXCde0bqaPT78chIIsDGuJ17Y="
  app: sous-chef-assistant


